### ISSUE TITLE
Replace input type on token field

### ISSUE THREAD

**Issue by juergenweb** [dominiquevienne/honeypot#2]
Hello dominique,

this was a misunterstanding. I dont mean the honeypot field, I mean the token field. The token field will not be hidden with JS.

Maybe you could change the input type of the token field from text to hidden.

`private $_tokenInputType                = 'hidden'; //line 30 of Form.php`

So no need to hide it with CSS.

Best regards

**Comment by dominiquevienne** [comment]
@juergenweb 
You are right... Default type value is now hidden for token field
Possibility has been added through object construction to change this value using the $configuration variable see v2.1.4-stable
